package view;

import controller.*;
import model.*;
import javafx.fxml.FXML;

import java.sql.*;
import java.time.LocalDateTime;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;

public class ViewCaseDetailsController{
	private DatabaseConnection database = new DatabaseConnection();
	private Connection connection;
	private Statement statement;
	private ResultSet resultSet;
	@FXML
	private TableView<Deadline> deadlineTable;
	@FXML
	private TableColumn<Deadline, String> deadlineTitleColumn;
	@FXML
	private TableColumn<Deadline, LocalDateTime> deadlineDateColumn;
	@FXML
	private TableColumn<Deadline, String> deadlineStatusColumn;
	@FXML
	private TableView<Appointment> appointmentTable;
	@FXML
	private TableColumn<Deadline, String> appointmentTitleColumn;
	@FXML
	private TableColumn<Deadline, LocalDateTime> appointmentDateColumn;
	@FXML
	private TableColumn<Deadline, LocalDateTime> appointmentLocColumn;
	@FXML
	private TableColumn<Deadline, String> appointmentColumn;
	@FXML
	private Label caseTitleLabel;
	@FXML
	private Label caseStatusLabel;
	@FXML
	private Label caseDateAddLabel;
	@FXML
	private Label clientNameLabel;
	@FXML
	private Label clientPhoneLabel;
	@FXML
	private Label clientEmailLabel;

	private Stage dialogStage;
	private Case c;

	public void setCase(Case c){
		this.c = c;
	}

	public void setDialogStage(Stage dialogStage){
		this.dialogStage = dialogStage;
	}

	// Event Listener on Button.onAction
	@FXML
	public void handleEdit(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("edit to be implemented soon");
	}
	// Event Listener on Button.onAction
	@FXML
	public void handleClose(ActionEvent event) {
		dialogStage.close();
	}


	public void setDetails() {
		// TODO Auto-generated method stub
		caseTitleLabel.setText(c.getTitle());
		caseStatusLabel.setText(c.getStatus());
		caseDateAddLabel.setText(c.getDateAdded().toString());

		deadlineTable.setItems(c.getDeadlines());
		deadlineTitleColumn.setCellValueFactory(new PropertyValueFactory<Deadline,String>("title"));
		deadlineDateColumn.setCellValueFactory(new PropertyValueFactory<Deadline,LocalDateTime>("date"));

		if(c.getClient() != null){
			clientNameLabel.setText(c.getClient().getName());
			clientPhoneLabel.setText(c.getClient().getPhone());
			clientEmailLabel.setText(c.getClient().getEmail());
		}
	}
}
