package controller;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class EditCaseDetailsController {
	@FXML
	private TextField caseTitleField;
	@FXML
	private TableView clientTable;
	@FXML
	private TableColumn clientNameColumn;
	@FXML
	private TableColumn clientPhoneColumn;
	@FXML
	private TableColumn clientEmailColumn;
	@FXML
	private TableView deadlineTable;
	@FXML
	private TableColumn deadlineTitleColumn;
	@FXML
	private TableColumn deadlineDateColumn;
	@FXML
	private TableView appointmentTable;
	@FXML
	private TableColumn appointmentTitleColumn;
	@FXML
	private TableColumn appointmentLocationColumn;
	@FXML
	private TableColumn appointmentDateColumn;

	// Event Listener on Button.onAction
	@FXML
	public void addDeadline(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void deleteDeadline(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void editDeadline(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void editAppointment(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addAppointment(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void deleteAppointment(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void handleSubmit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void handleClose(ActionEvent event) {
		// TODO Autogenerated
	}
}
